### PR TITLE
provide Debian 9.0 (Stretch) Specific default aliases

### PR DESCRIPTION
**Pull request by teadur**

### CODE REVIEW

**Comment by trombik** [comment]
as we do not have Debian 9.0 box image, I cannot confirm its default aliases. in 8.6, the following commands showed the `/etc/aliases` has a single alias, `postmaster`. how did you get the list?

```
vagrant@default-debian-86-amd64:~$ sudo su
root@default-debian-86-amd64:/home/vagrant# rm /etc/aliases
root@default-debian-86-amd64:/home/vagrant# dpkg-reconfigure postfix
(choose `Internet site` and accept all the defaults)
setting synchronous mail queue updates: false
mailname is not a fully qualified domain name.  Not changing /etc/mailname.
setting destinations: $myhostname, localhost.$mydomain, localhost
setting relayhost: 
setting mynetworks: 127.0.0.0/8 10.0.2.0/24 [::1]/128 [fe80::]/64
setting mailbox_size_limit: 0
setting recipient_delimiter: +
setting inet_interfaces: all
setting inet_protocols: all
/etc/aliases does not exist, creating it.
WARNING: /etc/aliases exists, but does not have a root alias.

Postfix is now set up with the changes above.  If you need to make changes, edit
/etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
values, see postconf(1).

After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.

Running newaliases
Processing triggers for libc-bin (2.19-18+deb8u6) ...
root@default-debian-86-amd64:/home/vagrant# cat /etc/aliases
# See man 5 aliases for format
postmaster:    root
```

**Comment by teadur** [comment]
I took random stretch machine where i havent modified the alises file by hand and it contained that list,  but it seems you are correct clean install of stretch, after installing postfix only postmaster:root is provided.
I guess daemons add aliases to that file when they are installed.

**Comment by trombik** [comment]
you need to merge `master` branch as i have released new version that supports Debian. see https://github.com/reallyenglish/ansible-role-postfix/pull/32/commits/1a96e80b58b270994cad2309d140fa42338c2347 for the place you need to change your branch.

**Comment by teadur** [comment]
I'll try to get correct patch working, but i have figured out where i got the initial long list, by default Debian installs exim4 https://wiki.debian.org/Debate/DefaultMTA

And it seems that exim4 has this list:

grep usenet /var/lib/dpkg/info/*
/var/lib/dpkg/info/exim4-config.postinst:for i in postmaster nobody hostmaster usenet news webmaster www ftp abuse noc security ; do

As of this role is ment for configuring postfix package, postfix default seem to make more sense ?

**Comment by teadur** [comment]
On the other hand having more aliases doesnot hurt anyone, so decide one way or another and i shall make my pull according do it.

**Comment by trombik** [comment]
#34 has been merged

**Pull request closed without merging**
